import { title } from "process";

export type Technician = {
  id: number;
  name: string;
  title: string;
  image: string;
  experience: string;
  specialties: string[];
  rating: number;
  certifications: string[];
  completedJobs: number;
};

export const techniciansData: Technician[] = [
  {
    id: 1,
    name: "Adrian Foster",
    title: "Senior Smart Home Specialist",
    image: "https://randomuser.me/api/portraits/men/31.jpg",
    experience: "8+ Years",
    specialties: ["Smart Home", "IoT Devices", "Home Automation"],
    rating: 4.9,
    certifications: ["Google Nest Pro", "Amazon Alexa Certified", "CompTIA A+"],
    completedJobs: 1200,
  },
  {
    id: 2,
    name: "Jasmine Wu",
    title: "Network & Security Expert",
    image: "https://randomuser.me/api/portraits/women/32.jpg",
    experience: "6+ Years",
    specialties: ["WiFi Networks", "Cybersecurity", "Business Solutions"],
    rating: 4.8,
    certifications: ["Cisco Certified", "Security+", "Network+"],
    completedJobs: 950,
  },
  {
    id: 3,
    name: "Derek Simmons",
    title: "Audio/Video Technician",
    image: "https://randomuser.me/api/portraits/men/33.jpg",
    experience: "10+ Years",
    specialties: ["Home Theater", "Audio Systems", "TV Installation"],
    rating: 4.9,
    certifications: ["THX Certified", "CEDIA Installer", "Sony Pro"],
    completedJobs: 1500,
  },
  {
    id: 4,
    name: "Natalie Brooks",
    title: "Mobile Device Specialist",
    image: "https://randomuser.me/api/portraits/women/34.jpg",
    experience: "5+ Years",
    specialties: ["Mobile Repair", "Data Recovery", "Device Setup"],
    rating: 4.7,
    certifications: ["Apple Certified", "Samsung Certified", "iFixit Pro"],
    completedJobs: 800,
  },
  {
    id: 5,
    name: "Priya Patel",
    title: "IT Support Specialist",
    image: "https://randomuser.me/api/portraits/women/35.jpg",
    experience: "7+ Years",
    specialties: ["IT Support", "Network Setup", "Troubleshooting"],
    rating: 4.8,
    certifications: ["CompTIA ITF+", "Microsoft Certified"],
    completedJobs: 1100,
  },
  {
    id: 6,
    name: "Leonardo Costa",
    title: "Home Office Expert",
    image: "https://randomuser.me/api/portraits/men/36.jpg",
    experience: "9+ Years",
    specialties: ["Home Office", "Printer Setup", "WiFi"],
    rating: 4.9,
    certifications: ["HP Certified", "Cisco CCNA"],
    completedJobs: 1300,
  },
  {
    id: 7,
    name: "Megan O'Connor",
    title: "Device Security Specialist",
    image: "https://randomuser.me/api/portraits/women/37.jpg",
    experience: "6+ Years",
    specialties: ["Device Security", "Malware Removal", "Data Protection"],
    rating: 4.7,
    certifications: ["Security+", "Certified Ethical Hacker"],
    completedJobs: 900,
  },
  {
    id: 8,
    name: "Samuel Grant",
    title: "PC & Laptop Technician",
    image: "https://randomuser.me/api/portraits/men/38.jpg",
    experience: "8+ Years",
    specialties: ["PC Repair", "Laptop Repair", "Upgrades"],
    rating: 4.8,
    certifications: ["CompTIA A+", "Dell Certified"],
    completedJobs: 1150,
  },
  {
    id: 9,
    name: "Tina Novak",
    title: "Printer & Scanner Expert",
    image: "https://randomuser.me/api/portraits/women/39.jpg",
    experience: "5+ Years",
    specialties: ["Printer Setup", "Scanner Setup", "Troubleshooting"],
    rating: 4.6,
    certifications: ["HP Certified", "Canon Certified"],
    completedJobs: 700,
  },
  {
    id: 10,
    name: "Victor Ivanov",
    title: "General Tech Support",
    image: "https://randomuser.me/api/portraits/men/40.jpg",
    experience: "10+ Years",
    specialties: ["Tech Support", "Device Setup", "Customer Service"],
    rating: 4.9,
    certifications: ["CompTIA A+", "Microsoft Certified"],
    completedJobs: 1600,
  },
  {
    id: 11,
    name: "Sophie Laurent",
    title: "Security Camera Installer",
    image: "https://randomuser.me/api/portraits/women/41.jpg",
    experience: "7+ Years",
    specialties: ["Security Cameras", "Home Security", "Installation"],
    rating: 4.8,
    certifications: ["Ring Certified", "ADT Installer"],
    completedJobs: 1050,
  },
  {
    id: 12,
    name: "Omar Farouk",
    title: "WiFi Optimization Specialist",
    image: "https://randomuser.me/api/portraits/men/42.jpg",
    experience: "6+ Years",
    specialties: ["WiFi", "Network Optimization", "Troubleshooting"],
    rating: 4.7,
    certifications: ["Cisco CCNA", "CompTIA Network+"],
    completedJobs: 950,
  },
  {
    id: 13,
    name: "Lara Schmidt",
    title: "Smart Home Installer",
    image: "https://randomuser.me/api/portraits/women/43.jpg",
    experience: "8+ Years",
    specialties: ["Smart Home", "IoT", "Automation"],
    rating: 4.9,
    certifications: ["Google Nest Pro", "Amazon Alexa Certified"],
    completedJobs: 1200,
  },
  {
    id: 14,
    name: "Rafael Mendes",
    title: "Data Recovery Specialist",
    image: "https://randomuser.me/api/portraits/men/44.jpg",
    experience: "9+ Years",
    specialties: ["Data Recovery", "Backup", "Storage"],
    rating: 4.8,
    certifications: ["CompTIA Server+", "Microsoft Certified"],
    completedJobs: 1400,
  },
  {
    id: 15,
    name: "Carmen Diaz",
    title: "Smart Doorstep Support Specialist",
    image: "https://randomuser.me/api/portraits/women/45.jpg",
    experience: "5+ Years",
    specialties: ["Tech Support", "Device Setup", "Customer Service"],
    rating: 4.7,
    certifications: ["CompTIA ITF+", "Apple Certified"],
    completedJobs: 800,
  },
  {
    id: 16,
    name: "Jared Kim",
    title: "Gaming PC Expert",
    image: "https://randomuser.me/api/portraits/men/46.jpg",
    experience: "7+ Years",
    specialties: ["Gaming PCs", "Custom Builds", "Upgrades"],
    rating: 4.8,
    certifications: ["CompTIA A+", "NVIDIA Certified"],
    completedJobs: 1100,
  },
  {
    id: 17,
    name: "Bianca Rossi",
    title: "Internet Troubleshooter",
    image: "https://randomuser.me/api/portraits/women/47.jpg",
    experience: "6+ Years",
    specialties: ["Internet", "WiFi", "Network"],
    rating: 4.7,
    certifications: ["Cisco CCNA", "CompTIA Network+"],
    completedJobs: 900,
  },
  {
    id: 18,
    name: "Marcus Lee",
    title: "General Tech Support",
    image: "https://randomuser.me/api/portraits/men/48.jpg",
    experience: "8+ Years",
    specialties: ["Tech Support", "Device Setup", "Customer Service"],
    rating: 4.8,
    certifications: ["CompTIA A+", "Microsoft Certified"],
    completedJobs: 1200,
  },
  {
    id: 19,
    name: "Yara Khalil",
    title: "Smart Lighting Specialist",
    image: "https://randomuser.me/api/portraits/women/49.jpg",
    experience: "7+ Years",
    specialties: ["Smart Lighting", "Home Automation", "IoT"],
    rating: 4.8,
    certifications: ["Philips Hue Certified", "Google Nest Pro"],
    completedJobs: 1100,
  },
  {
    id: 20,
    name: "Dwayne Carter",
    title: "TV Mounting Expert",
    image: "https://randomuser.me/api/portraits/men/50.jpg",
    experience: "9+ Years",
    specialties: ["TV Mounting", "Cable Management", "Home Theater"],
    rating: 4.9,
    certifications: ["CEDIA Installer", "Sony Pro"],
    completedJobs: 1300,
  },
  {
    id: 21,
    name: "Marta Silva",
    title: "Home Office Setup Specialist",
    image: "https://randomuser.me/api/portraits/women/51.jpg",
    experience: "6+ Years",
    specialties: ["Home Office", "Printer Setup", "WiFi"],
    rating: 4.7,
    certifications: ["HP Certified", "Cisco CCNA"],
    completedJobs: 900,
  },
  {
    id: 22,
    name: "Stefan Novak",
    title: "Computer Tune-Up Expert",
    image: "https://randomuser.me/api/portraits/men/52.jpg",
    experience: "8+ Years",
    specialties: ["Computer Tune-Up", "Maintenance", "Upgrades"],
    rating: 4.8,
    certifications: ["CompTIA A+", "Dell Certified"],
    completedJobs: 1150,
  },
  {
    id: 23,
    name: "Nadia Petrova",
    title: "WiFi Troubleshooting Specialist",
    image: "https://randomuser.me/api/portraits/women/53.jpg",
    experience: "5+ Years",
    specialties: ["WiFi", "Network", "Troubleshooting"],
    rating: 4.6,
    certifications: ["Cisco CCNA", "CompTIA Network+"],
    completedJobs: 700,
  },
  {
    id: 24,
    name: "Jalen Brooks",
    title: "General Tech Support",
    image: "https://randomuser.me/api/portraits/men/54.jpg",
    experience: "10+ Years",
    specialties: ["Tech Support", "Device Setup", "Customer Service"],
    rating: 4.9,
    certifications: ["CompTIA A+", "Microsoft Certified"],
    completedJobs: 1600,
  },
  {
    id: 25,
    name: "Lina Müller",
    title: "Smart Thermostat Installer",
    image: "https://randomuser.me/api/portraits/women/55.jpg",
    experience: "7+ Years",
    specialties: ["Smart Thermostat", "Home Automation", "IoT"],
    rating: 4.8,
    certifications: ["Google Nest Pro", "Amazon Alexa Certified"],
    completedJobs: 1050,
  },
  {
    id: 26,
    name: "Owen Murphy",
    title: "Network Troubleshooter",
    image: "https://randomuser.me/api/portraits/men/56.jpg",
    experience: "6+ Years",
    specialties: ["Network", "WiFi", "Troubleshooting"],
    rating: 4.7,
    certifications: ["Cisco CCNA", "CompTIA Network+"],
    completedJobs: 950,
  },
  {
    id: 27,
    name: "Sofia Romano",
    title: "Smart Home Setup Specialist",
    image: "https://randomuser.me/api/portraits/women/57.jpg",
    experience: "8+ Years",
    specialties: ["Smart Home", "IoT", "Automation"],
    rating: 4.9,
    certifications: ["Google Nest Pro", "Amazon Alexa Certified"],
    completedJobs: 1200,
  },
  {
    id: 28,
    name: "Hugo Dubois",
    title: "Printer Repair Expert",
    image: "https://randomuser.me/api/portraits/men/58.jpg",
    experience: "9+ Years",
    specialties: ["Printer Repair", "Scanner Setup", "Troubleshooting"],
    rating: 4.8,
    certifications: ["HP Certified", "Canon Certified"],
    completedJobs: 1400,
  },
  {
    id: 29,
    name: "Mina Hassan",
    title: "Device Setup Specialist",
    image: "https://randomuser.me/api/portraits/women/59.jpg",
    experience: "6+ Years",
    specialties: ["Device Setup", "Tech Support", "Customer Service"],
    rating: 4.7,
    certifications: ["CompTIA ITF+", "Apple Certified"],
    completedJobs: 800,
  },
  {
    id: 30,
    name: "Anders Berg",
    title: "Home Theater Installer",
    image: "https://randomuser.me/api/portraits/men/60.jpg",
    experience: "7+ Years",
    specialties: ["Home Theater", "Audio Systems", "TV Installation"],
    rating: 4.8,
    certifications: ["THX Certified", "CEDIA Installer"],
    completedJobs: 1100,
  },
];
