// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsqgzsvsvgquqqevscpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzcWd6c3ZzdmdxdXFxZXZzY3B2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MTc4OTUsImV4cCI6MjA2MzQ5Mzg5NX0.DW6bOMFYnRVR46Fw_wzgiaNtMZFOlSXuo_NON6oUQ88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);